const sellers = [
  {
    _id: '6008bfc6851a127ae59215ee',
    name: 'WardSalad',
    sales: 67,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_69.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_6.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_59.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_20.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_25.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_2.jpg',
        ],
        id: 4,
        name: 'ludicrous bow',
        description: 'It was quite ironic, really. It was something Greg had said he would never wish upon anyone a million times, yet here he was knowingly letting it happen to one of his best friends. He rationalized that it would ultimately make Michael a better person and that no matter how uncomfortable, everyone should experience racism at least once in their lifetime.',
        price: '49.55',
        stock: 8,
        sizes: true,
        rating: 3,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_78.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_96.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_30.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_86.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_97.jpg',
        ],
        id: 6,
        name: 'parsimonious toy car',
        description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
        price: '43.15',
        stock: 15,
        sizes: false,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_12.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_35.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_68.jpg',
        ],
        id: 16,
        name: 'boring bow',
        description: 'There are different types of secrets. She had held onto plenty of them during her life, but this one was different. She found herself holding onto the worst type.',
        price: '92.58',
        stock: 5,
        sizes: false,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_88.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_46.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_50.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_6.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_27.jpg',
        ],
        id: 24,
        name: 'lovely plush cat',
        description: "After all the time and effort she'd invested into it, she never thought that it would be anything but wonderful. It goes without saying that things didn't work out quite as she expected.",
        price: '60.47',
        stock: 6,
        sizes: true,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_92.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_29.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_76.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_67.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_5.jpg',
        ],
        id: 35,
        name: 'jazzy sidewalk',
        description: "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but he'd finally taken the hint and asked her out.",
        price: '59.36',
        stock: 11,
        sizes: false,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_66.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_32.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_70.jpg',
        ],
        id: 36,
        name: 'last rolling pin',
        description: "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but he'd finally taken the hint and asked her out.",
        price: '26.82',
        stock: 15,
        sizes: false,
        rating: 0,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_93.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_89.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_48.jpg',
        ],
        id: 53,
        name: 'deep pair of earrings',
        description: 'He closed his eyes, the sun beating down on face and he smiled. He smiled for the first time in as long as he could remember. To her surprise, she found what she least expected to see.',
        price: '30.87',
        stock: 8,
        sizes: true,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_19.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_89.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_30.jpg',
        ],
        id: 85,
        name: 'abundant packet of seeds',
        description: "Don't be scared. The things out there that are unknown aren't scary in themselves. They are just unknown at the moment. Take the time to know them before you list them as scary. Then the world will be a much less scary place for you.",
        price: '14.24',
        stock: 8,
        sizes: true,
        rating: 3,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215ef',
    name: 'KatlynSnow',
    sales: 718,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_31.jpg',
        ],
        id: 14,
        name: 'inquisitive hair tie',
        description: 'Greg understood that this situation would make Michael terribly uncomfortable. Michael simply had no idea what was about to come and even though Greg could prevent it from happening, he opted to let it happen.',
        price: '93.73',
        stock: 1,
        sizes: true,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_2.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_41.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_46.jpg',
        ],
        id: 17,
        name: 'helpless flowers',
        description: "He may have been able to work one out if he had a bit of time to think things through, but time was something he didn't have. A choice needed to be made, and it needed to be made quickly.",
        price: '41.14',
        stock: 9,
        sizes: true,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_46.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_12.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_67.jpg',
        ],
        id: 57,
        name: 'lovely spool of wire',
        description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
        price: '64.48',
        stock: 7,
        sizes: false,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_91.jpg',
        ],
        id: 77,
        name: 'jazzy puddle',
        description: '',
        price: '25.17',
        stock: 10,
        sizes: true,
        rating: 5,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f0',
    name: 'WardFriction',
    sales: 438,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_30.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_19.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_20.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_69.jpg',
        ],
        id: 19,
        name: 'unkempt cowboy hat',
        description: '',
        price: '5.72',
        stock: 2,
        sizes: false,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_12.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_56.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_70.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_95.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_53.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_45.jpg',
        ],
        id: 21,
        name: 'cowardly seat belt',
        description: 'But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.',
        price: '39.94',
        stock: 11,
        sizes: false,
        rating: 2,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f1',
    name: 'MayaSnails',
    sales: 811,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_38.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_65.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_22.jpg',
        ],
        id: 9,
        name: 'homeless stick of incense',
        description: 'It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down.',
        price: '77.33',
        stock: 13,
        sizes: false,
        rating: 2,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_22.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_34.jpg',
        ],
        id: 13,
        name: 'jazzy tire swing',
        description: "Sleeping in his car was never the plan but sometimes things don't work out as planned. This had been his life for the last three months and he was just beginning to get used to it.",
        price: '54.55',
        stock: 3,
        sizes: true,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_25.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_55.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_44.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_79.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_98.jpg',
        ],
        id: 43,
        name: 'boring pair of earrings',
        description: 'He closed his eyes, the sun beating down on face and he smiled. He smiled for the first time in as long as he could remember. To her surprise, she found what she least expected to see.',
        price: '72.48',
        stock: 12,
        sizes: false,
        rating: 4,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_13.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_35.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_65.jpg',
        ],
        id: 87,
        name: 'future turtle',
        description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
        price: '83.25',
        stock: 4,
        sizes: false,
        rating: 5,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f2',
    name: 'UsaamahFarm',
    sales: 369,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_50.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_34.jpg',
        ],
        id: 7,
        name: 'famous plush bear',
        description: 'It was a weird concept. Why would I really need to generate a random paragraph? Could I actually learn something from doing so? All these questions were running through her head as she pressed the generate button.',
        price: '16.32',
        stock: 4,
        sizes: true,
        rating: 3,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_2.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_66.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_65.jpg',
        ],
        id: 84,
        name: 'noxious spool of wire',
        description: 'There are different types of secrets. She had held onto plenty of them during her life, but this one was different. She found herself holding onto the worst type.',
        price: '69.12',
        stock: 0,
        sizes: false,
        rating: 5,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f3',
    name: 'RohanLow',
    sales: 291,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_86.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_89.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_88.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_100.jpg',
        ],
        id: 44,
        name: 'careful umbrella',
        description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
        price: '48.66',
        stock: 6,
        sizes: false,
        rating: 5,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f4',
    name: 'NafisaWrist',
    sales: 821,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_79.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_28.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
        ],
        id: 25,
        name: 'homeless bottle of soda',
        description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
        price: '64.88',
        stock: 12,
        sizes: true,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_80.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_36.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_6.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_8.jpg',
        ],
        id: 26,
        name: 'green radio',
        description: "At that, they probably didn't have too much time after they detected us orbiting and intending to land. And if that were true, there could be only one place where their civilization was hidden.",
        price: '68.74',
        stock: 5,
        sizes: true,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_37.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
        ],
        id: 28,
        name: 'ludicrous pair of socks',
        description: "Sleeping in his car was never the plan but sometimes things don't work out as planned. This had been his life for the last three months and he was just beginning to get used to it.",
        price: '14.70',
        stock: 13,
        sizes: true,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_94.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
        ],
        id: 51,
        name: 'bright empty jar',
        description: "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but he'd finally taken the hint and asked her out.",
        price: '95.16',
        stock: 10,
        sizes: true,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_72.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_74.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_83.jpg',
        ],
        id: 63,
        name: 'fertile bag of rubber bands',
        description: "Don't be scared. The things out there that are unknown aren't scary in themselves. They are just unknown at the moment. Take the time to know them before you list them as scary. Then the world will be a much less scary place for you.",
        price: '36.60',
        stock: 7,
        sizes: false,
        rating: 0,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_87.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_27.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_54.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_60.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_73.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_8.jpg',
        ],
        id: 69,
        name: 'abundant tire swing',
        description: 'She watched as birds flew past the window bolted shut. She couldn’t reach it if she wanted too, with that hole in the floor. She thought she could escape through it but three stories is a bit far down.',
        price: '76.63',
        stock: 10,
        sizes: true,
        rating: 2,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_93.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_27.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_32.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_76.jpg',
        ],
        id: 94,
        name: 'ludicrous couch',
        description: 'It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down.',
        price: '58.55',
        stock: 15,
        sizes: false,
        rating: 4,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f5',
    name: 'FreyRun',
    sales: 27,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_88.jpg',
        ],
        id: 22,
        name: 'old pair of handcuffs',
        description: 'Sitting in the sun, away from everyone who had done him harm in the past, he quietly listened to those who roamed by. He felt at peace in the moment, hoping it would last, but knowing the reprieve would soon come to an end.',
        price: '44.18',
        stock: 4,
        sizes: false,
        rating: 4,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_10.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_6.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_37.jpg',
        ],
        id: 29,
        name: 'last pair of earrings',
        description: 'But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust.',
        price: '80.39',
        stock: 5,
        sizes: false,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
        ],
        id: 73,
        name: 'good magnet',
        description: "At that, they probably didn't have too much time after they detected us orbiting and intending to land. And if that were true, there could be only one place where their civilization was hidden.",
        price: '13.22',
        stock: 6,
        sizes: false,
        rating: 0,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_53.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_87.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_90.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_55.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_93.jpg',
        ],
        id: 75,
        name: 'glamorous umbrella',
        description: 'It was a weird concept. Why would I really need to generate a random paragraph? Could I actually learn something from doing so? All these questions were running through her head as she pressed the generate button.',
        price: '25.40',
        stock: 4,
        sizes: false,
        rating: 3,
      },
    ],
  },
  {
    _id: '6008bfc6851a127ae59215f6',
    name: 'MohammedCounty',
    sales: 922,
    products: [
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_44.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_10.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_11.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_31.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_14.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_20.jpg',
        ],
        id: 15,
        name: 'obsequious candle',
        description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
        price: '64.90',
        stock: 7,
        sizes: false,
        rating: 5,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_17.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_52.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_43.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_62.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_90.jpg',
        ],
        id: 27,
        name: 'ill-informed lamp',
        description: 'Sitting in the sun, away from everyone who had done him harm in the past, he quietly listened to those who roamed by. He felt at peace in the moment, hoping it would last, but knowing the reprieve would soon come to an end.',
        price: '71.34',
        stock: 3,
        sizes: true,
        rating: 1,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_72.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_100.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_82.jpg',
        ],
        id: 49,
        name: 'inquisitive stop sign',
        description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
        price: '85.00',
        stock: 13,
        sizes: true,
        rating: 3,
      },
      {
        images: [
          'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_59.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_34.jpg',
          'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
        ],
        id: 70,
        name: 'expensive bar of soap',
        description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
        price: '70.75',
        stock: 13,
        sizes: false,
        rating: 3,
      },
    ],
  },
];

const seller = {
  _id: '6008bfc6851a127ae59215f4',
  name: 'NafisaWrist',
  sales: 821,
  products: [
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_79.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_28.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
      ],
      id: 25,
      name: 'homeless bottle of soda',
      description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
      price: '64.88',
      stock: 12,
      sizes: true,
      rating: 1,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_80.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_36.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_6.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_8.jpg',
      ],
      id: 26,
      name: 'green radio',
      description: "At that, they probably didn't have too much time after they detected us orbiting and intending to land. And if that were true, there could be only one place where their civilization was hidden.",
      price: '68.74',
      stock: 5,
      sizes: true,
      rating: 1,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_37.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
      ],
      id: 28,
      name: 'ludicrous pair of socks',
      description: "Sleeping in his car was never the plan but sometimes things don't work out as planned. This had been his life for the last three months and he was just beginning to get used to it.",
      price: '14.70',
      stock: 13,
      sizes: true,
      rating: 5,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_94.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
      ],
      id: 51,
      name: 'bright empty jar',
      description: "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but he'd finally taken the hint and asked her out.",
      price: '95.16',
      stock: 10,
      sizes: true,
      rating: 5,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_72.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_74.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_83.jpg',
      ],
      id: 63,
      name: 'fertile bag of rubber bands',
      description: "Don't be scared. The things out there that are unknown aren't scary in themselves. They are just unknown at the moment. Take the time to know them before you list them as scary. Then the world will be a much less scary place for you.",
      price: '36.60',
      stock: 7,
      sizes: false,
      rating: 0,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_87.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_27.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_54.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_60.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_73.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_8.jpg',
      ],
      id: 69,
      name: 'abundant tire swing',
      description: 'She watched as birds flew past the window bolted shut. She couldn’t reach it if she wanted too, with that hole in the floor. She thought she could escape through it but three stories is a bit far down.',
      price: '76.63',
      stock: 10,
      sizes: true,
      rating: 2,
    },
    {
      images: [
        'https://fec-product-pictures.s3.amazonaws.com/product_93.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_27.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_32.jpg',
        'https://fec-product-pictures.s3.amazonaws.com/product_76.jpg',
      ],
      id: 94,
      name: 'ludicrous couch',
      description: 'It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down.',
      price: '58.55',
      stock: 15,
      sizes: false,
      rating: 4,
    },
  ],
};

const products = [
  {
    images: [
      'https://fec-product-pictures.s3.amazonaws.com/product_44.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_10.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_11.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_31.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_14.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_20.jpg',
    ],
    id: 15,
    name: 'obsequious candle',
    description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
    price: '64.90',
    stock: 7,
    sizes: false,
    rating: 5,
  },
  {
    images: [
      'https://fec-product-pictures.s3.amazonaws.com/product_17.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_52.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_43.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_61.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_71.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_62.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_90.jpg',
    ],
    id: 27,
    name: 'ill-informed lamp',
    description: 'Sitting in the sun, away from everyone who had done him harm in the past, he quietly listened to those who roamed by. He felt at peace in the moment, hoping it would last, but knowing the reprieve would soon come to an end.',
    price: '71.34',
    stock: 3,
    sizes: true,
    rating: 1,
  },
  {
    images: [
      'https://fec-product-pictures.s3.amazonaws.com/product_72.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_100.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_82.jpg',
    ],
    id: 49,
    name: 'inquisitive stop sign',
    description: 'The trees, therefore, must be such old and primitive techniques that they thought nothing of them, deeming them so inconsequential that even savages like us would know of them and not be suspicious.',
    price: '85.00',
    stock: 13,
    sizes: true,
    rating: 3,
  },
  {
    images: [
      'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_59.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_34.jpg',
      'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
    ],
    id: 70,
    name: 'expensive bar of soap',
    description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
    price: '70.75',
    stock: 13,
    sizes: false,
    rating: 3,
  },
];

const product = {
  images: [
    'https://fec-product-pictures.s3.amazonaws.com/product_63.jpg',
    'https://fec-product-pictures.s3.amazonaws.com/product_59.jpg',
    'https://fec-product-pictures.s3.amazonaws.com/product_34.jpg',
    'https://fec-product-pictures.s3.amazonaws.com/product_3.jpg',
  ],
  id: 70,
  name: 'expensive bar of soap',
  description: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
  price: '70.75',
  stock: 13,
  sizes: false,
  rating: 3,
};

const productAlt = {
  images: [
    'https://fec-product-pictures.s3.amazonaws.com/product_94.jpg',
    'https://fec-product-pictures.s3.amazonaws.com/product_18.jpg',
  ],
  id: 51,
  name: 'bright empty jar',
  description: "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but he'd finally taken the hint and asked her out.",
  price: '95.16',
  stock: 0,
  sizes: true,
  rating: 5,
};

module.exports = {
  sellers, seller, products, product, productAlt,
};
